version: "3.9"

services: 
    cache:
        container_name: cache
        image: bitnami/redis:6.2.3
        environment: 
            - REDIS_PASSWORD=${REDIS_PWD}
        ports: 
            - "6379:6379"

    feed-database:
        container_name: feed-database
        image: postgres:13.2-alpine
        environment: 
            POSTGRES_PASSWORD: ${POSTGRESQL_PWD}
            POSTGRES_USER: ${POSTGRESQL_USER}
        volumes: 
            - ./feedData:/var/lib/postgresql/data
        ports: 
            - "5432:5432"

    profile-database:
        container_name: profile-database
        image: mongo:4.4
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
        volumes: 
            - ./profileData:/data/db
        ports: 
            - "27017:27017"

    profile-service:
        build: ./profile-service
        container_name: profile-service
        ports: 
            - "5000:80"
        depends_on: 
            - cache
            - profile-database