services: 
    profile-service:
        build: ./profile-service
        container_name: profile-service
        ports: 
            - "5000:80"
        depends_on: 
            - cache
            - profile-database